### ISSUE TITLE
Should GitHub Pages be disabled for this repo?

### ISSUE THREAD

**Issue by samglover** [SuffolkLITLab/resource-map-how-to#1]
It looks like the website at suffolklitlab.org/resource-map-how-to doesn't actually reflect the content of this repo, which is meant to help people replicate https://github.com/SuffolkLITLab/resource-map for themselves. All that information is in the README.md, not the generated website.

So should GitHub Pages be disabled for this repo, @colarusso?

**Comment by colarusso** [comment]
no longer needed, pages disabled
